# common/config.yaml
project:
  name: ai-trader
  root: /var/www/vhosts/snapdiscounts.nl/ai-trader
  venv: /var/www/vhosts/snapdiscounts.nl/ai-trader/.venv
  user: snapdiscounts
  group: psacln
  parquet_root: /var/www/vhosts/snapdiscounts.nl/ai-trader/data/parquet
  logs_root: /var/www/vhosts/snapdiscounts.nl/ai-trader/logs

redis:
  host: localhost
  port: 6379
  db: 0
  streams:
    ws_events_mini_ticker: ws_events:mini_ticker
    ws_events_bbo: ws_events:bbo
    ws_events_depth10: ws_events:depth10
    selection_out: selection.out
    features_out: features.out
    order_cmds: order_cmds
    risk_out: risk.out
    exec_events: exec.events
    fills_events: fills.events
    alerts: alerts
